from __future__ import annotations

import argparse
import html
import operator
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Any, Iterator, Literal, TypedDict

try:
    from langgraph.graph import END, START, StateGraph
    from langgraph.types import Send
except ImportError as exc:  # pragma: no cover
    raise RuntimeError(
        "LangGraph is required. Run this demo in the py311 environment."
    ) from exc


# ---------------------------------------------------------------------------
# Knowledge point 1: State is the shared data contract of the graph.
# ---------------------------------------------------------------------------
# MainState is intentionally close to the real project:
# - query: current user question
# - papers: retrieved material
# - selected_agents: router result
# - agent_outputs: parallel agent results, merged by operator.add
# - final_answer: final summary generated by the report node
#
# The important LangGraph detail is Annotated[list, operator.add].
# When multiple parallel branches return {"agent_outputs": [...]}, LangGraph
# appends those lists instead of letting the last branch overwrite the others.


class Paper(TypedDict):
    title: str
    tags: list[str]
    summary: str


class AgentOutput(TypedDict):
    agent_name: str
    title: str
    content: str


class MainState(TypedDict, total=False):
    query: str
    normalized_query: str
    route_reason: str
    selected_agents: list[str]
    papers: list[Paper]
    agent_outputs: Annotated[list[AgentOutput], operator.add]
    final_answer: str
    trace: Annotated[list[str], operator.add]


class AgentTaskState(TypedDict):
    agent_name: str
    query: str
    papers: list[Paper]


@dataclass(frozen=True)
class AgentSpec:
    title: str
    focus: str


AGENTS: dict[str, AgentSpec] = {
    "survey_agent": AgentSpec(
        title="Survey Agent",
        focus="summarize background, trends, and representative work",
    ),
    "method_agent": AgentSpec(
        title="Method Agent",
        focus="compare methods, architectures, and technical mechanisms",
    ),
    "innovation_agent": AgentSpec(
        title="Innovation Agent",
        focus="identify contributions, novelty, and publishable ideas",
    ),
    "limitation_agent": AgentSpec(
        title="Limitation Agent",
        focus="find risks, limitations, and follow-up opportunities",
    ),
}


MOCK_PAPERS: list[Paper] = [
    {
        "title": "Mamba: Linear-Time Sequence Modeling",
        "tags": ["method", "long context", "efficiency"],
        "summary": "Selective state spaces improve long sequence modeling with linear complexity.",
    },
    {
        "title": "StreamingVLM: Real-Time Understanding for Infinite Video",
        "tags": ["survey", "method", "limitation"],
        "summary": "Streaming inference uses compact context and cache reuse for long videos.",
    },
    {
        "title": "KV Cache Compression for Efficient LLM Inference",
        "tags": ["innovation", "method", "limitation"],
        "summary": "Cache pruning and compression reduce memory but can affect answer quality.",
    },
    {
        "title": "Long Video Understanding: A Survey",
        "tags": ["survey", "trend"],
        "summary": "Long-video research focuses on temporal grounding, memory, and efficient attention.",
    },
]


def create_initial_state(query: str) -> MainState:
    """Create a fresh state for one graph run."""
    return {
        "query": query,
        "normalized_query": "",
        "route_reason": "",
        "selected_agents": [],
        "papers": [],
        "agent_outputs": [],
        "final_answer": "",
        "trace": [],
    }


# ---------------------------------------------------------------------------
# Knowledge point 2: A node reads the current state and returns a partial update.
# ---------------------------------------------------------------------------


def normalize_question_node(state: MainState) -> dict[str, Any]:
    """Make the user question easier for retrieval and routing."""
    query = state["query"].strip()
    normalized = " ".join(query.lower().split())
    return {
        "normalized_query": normalized,
        "trace": [f"normalize_question -> {normalized}"],
    }


def retrieve_papers_node(state: MainState) -> dict[str, Any]:
    """A tiny local retriever that mimics the real FAISS retrieval step."""
    query = state["normalized_query"]
    words = set(query.replace(",", " ").split())

    scored: list[tuple[int, Paper]] = []
    for paper in MOCK_PAPERS:
        haystack = " ".join([paper["title"], *paper["tags"], paper["summary"]]).lower()
        score = sum(1 for word in words if word in haystack)
        scored.append((score, paper))

    papers = [paper for score, paper in sorted(scored, key=lambda item: -item[0]) if score > 0]
    if not papers:
        papers = MOCK_PAPERS[:2]
    return {
        "papers": papers[:3],
        "trace": [f"retrieve_papers -> {len(papers[:3])} papers"],
    }


def route_node(state: MainState) -> dict[str, Any]:
    """Select only the agents that are useful for this question."""
    query = state["normalized_query"]
    selected: list[str] = []

    if any(word in query for word in ["survey", "trend", "background", "overview", "综述", "趋势"]):
        selected.append("survey_agent")
    if any(word in query for word in ["method", "compare", "architecture", "方法", "架构", "比较"]):
        selected.append("method_agent")
    if any(word in query for word in ["innovation", "novel", "idea", "创新", "选题", "方向"]):
        selected.append("innovation_agent")
    if any(word in query for word in ["limitation", "risk", "weakness", "局限", "风险", "问题"]):
        selected.append("limitation_agent")

    # Research-direction questions need a wider decision context.
    if any(word in query for word in ["publish", "paper topic", "发论文", "研究方向"]):
        selected = list(AGENTS)

    if not selected:
        selected = ["survey_agent", "method_agent"]

    selected = list(dict.fromkeys(selected))
    reason = f"Selected {len(selected)} agent(s): {', '.join(selected)}"
    return {
        "selected_agents": selected,
        "route_reason": reason,
        "trace": [f"route -> {reason}"],
    }


# ---------------------------------------------------------------------------
# Knowledge point 3: Send creates dynamic parallel branches.
# ---------------------------------------------------------------------------
# The route node decides selected_agents. dispatch_agents converts that list
# into multiple Send objects. Each Send invokes run_agent_node with a small
# AgentTaskState, so each agent sees only the context it needs.


def dispatch_agents(state: MainState) -> list[Send]:
    return [
        Send(
            "run_agent",
            {
                "agent_name": agent_name,
                "query": state["query"],
                "papers": list(state["papers"]),
            },
        )
        for agent_name in state.get("selected_agents", [])
    ]


def run_agent_node(task: AgentTaskState) -> dict[str, Any]:
    """Run one specialist agent branch."""
    agent_name = task["agent_name"]
    spec = AGENTS[agent_name]

    # The sleep is short and deliberate: it makes streaming visualization easier
    # to observe without making the demo slow.
    time.sleep(0.25)

    paper_titles = ", ".join(paper["title"] for paper in task["papers"])
    content = (
        f"{spec.title} focuses on: {spec.focus}. "
        f"For query '{task['query']}', it uses papers: {paper_titles}."
    )
    return {
        "agent_outputs": [
            {
                "agent_name": agent_name,
                "title": spec.title,
                "content": content,
            }
        ],
        "trace": [f"{agent_name} -> completed"],
    }


def report_node(state: MainState) -> dict[str, Any]:
    """Reduce all parallel outputs into one final answer."""
    ordered_outputs = sorted(
        state.get("agent_outputs", []),
        key=lambda output: state.get("selected_agents", []).index(output["agent_name"]),
    )
    lines = [
        "# LangGraph Demo Result",
        "",
        f"Query: {state['query']}",
        f"Route: {state['route_reason']}",
        "",
        "## Agent Findings",
    ]
    for output in ordered_outputs:
        lines.extend(["", f"### {output['title']}", output["content"]])
    return {
        "final_answer": "\n".join(lines),
        "trace": ["report -> merged parallel outputs"],
    }


# ---------------------------------------------------------------------------
# Knowledge point 4: Build the graph topology.
# ---------------------------------------------------------------------------


def build_graph():
    graph = StateGraph(MainState)
    graph.add_node("normalize_question", normalize_question_node)
    graph.add_node("retrieve_papers", retrieve_papers_node)
    graph.add_node("route", route_node)
    graph.add_node("run_agent", run_agent_node)
    graph.add_node("report", report_node)

    graph.add_edge(START, "normalize_question")
    graph.add_edge("normalize_question", "retrieve_papers")
    graph.add_edge("retrieve_papers", "route")
    graph.add_conditional_edges("route", dispatch_agents, ["run_agent"])
    graph.add_edge("run_agent", "report")
    graph.add_edge("report", END)
    return graph.compile()


def run_demo(query: str) -> MainState:
    """Run the graph once and return the final state."""
    return build_graph().invoke(create_initial_state(query))


def stream_demo(query: str) -> Iterator[dict[str, Any]]:
    """Yield node-level updates for visualization."""
    state = create_initial_state(query)
    accumulated: MainState = dict(state)
    yield {
        "node": "START",
        "status": "completed",
        "state": dict(accumulated),
    }
    for update in build_graph().stream(state, stream_mode="updates"):
        for node, patch in update.items():
            _merge_update(accumulated, patch)
            event: dict[str, Any] = {
                "node": node,
                "status": "completed",
                "state": dict(accumulated),
            }
            if node == "run_agent" and patch.get("agent_outputs"):
                event["agent_name"] = patch["agent_outputs"][0]["agent_name"]
            yield event
    yield {
        "node": "END",
        "status": "completed",
        "state": dict(accumulated),
    }


def _merge_update(state: MainState, patch: dict[str, Any]) -> None:
    """Manually merge stream updates so the UI can show accumulated state."""
    for key, value in patch.items():
        if key in {"agent_outputs", "trace"}:
            state.setdefault(key, []).extend(value)
        else:
            state[key] = value


# ---------------------------------------------------------------------------
# Knowledge point 5: Visualize graph status.
# ---------------------------------------------------------------------------


def render_svg(
    state: MainState,
    active_node: str | None = None,
    completed_nodes: set[str] | None = None,
    completed_agents: set[str] | None = None,
) -> str:
    """Return a self-contained SVG that highlights current graph progress."""
    completed_nodes = completed_nodes or set()
    completed_agents = completed_agents or set()
    selected_agents = state.get("selected_agents", []) or list(AGENTS)

    def node_class(name: str) -> str:
        if name == active_node:
            return "active"
        if name in completed_nodes:
            return "done"
        return "pending"

    def agent_class(name: str) -> str:
        if name == active_node:
            return "active"
        if name in completed_agents:
            return "done"
        if name in selected_agents:
            return "pending"
        return "muted"

    agent_count = max(len(selected_agents), 1)
    width = 980
    height = 760
    start_x = 160
    center_x = width // 2
    agent_area_width = 620
    step = agent_area_width / agent_count
    agent_positions: list[tuple[str, float, float]] = []
    for index, agent_name in enumerate(selected_agents):
        x = center_x - agent_area_width / 2 + step * index + step / 2
        agent_positions.append((agent_name, x, 470))

    agent_edges = "\n".join(
        f'<path class="edge {agent_class(name)}" d="M {center_x} 360 L {x:.1f} 440" />'
        f'<path class="edge {agent_class(name)}" d="M {x:.1f} 500 L {center_x} 590" />'
        for name, x, _ in agent_positions
    )
    agent_nodes = "\n".join(
        _svg_circle_node(
            x=x,
            y=y,
            r=44,
            title=name.replace("_agent", "").upper(),
            subtitle=AGENTS[name].title,
            css=agent_class(name),
        )
        for name, x, y in agent_positions
    )
    trace_text = "\n".join(
        f'<text x="38" y="{650 + index * 22}" class="trace">[{index + 1}] {html.escape(item)}</text>'
        for index, item in enumerate(state.get("trace", [])[-4:])
    )
    paper_count = len(state.get("papers", []))
    selected_count = len(state.get("selected_agents", []))

    return f"""
<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" role="img">
  <style>
    .bg {{ fill: #061427; }}
    .grid {{ stroke: rgba(82, 150, 210, 0.16); stroke-width: 1; }}
    .label {{ fill: #d8ecff; font: 700 18px Arial, sans-serif; }}
    .small {{ fill: #8bb7da; font: 12px Arial, sans-serif; letter-spacing: 2px; }}
    .trace {{ fill: #8bb7da; font: 13px Consolas, monospace; }}
    .edge {{ fill: none; stroke-width: 2.5; stroke-dasharray: 9 8; }}
    .edge.pending {{ stroke: rgba(117, 165, 205, 0.38); }}
    .edge.done {{ stroke: #42d8ff; filter: drop-shadow(0 0 5px #42d8ff); }}
    .edge.active {{ stroke: #8ee8ff; filter: drop-shadow(0 0 8px #8ee8ff); }}
    .edge.muted {{ stroke: rgba(117, 165, 205, 0.14); }}
    .node-circle {{ stroke-width: 2; }}
    .pending .node-circle {{ fill: #0b2544; stroke: #4078a8; }}
    .done .node-circle {{ fill: #0e426f; stroke: #4bddff; filter: drop-shadow(0 0 8px #3fd4ff); }}
    .active .node-circle {{ fill: #115b8d; stroke: #b7f3ff; filter: drop-shadow(0 0 14px #61dcff); }}
    .muted .node-circle {{ fill: #0a1b31; stroke: rgba(83, 122, 155, 0.35); }}
    .node-title {{ fill: #ecf8ff; font: 700 15px Arial, sans-serif; text-anchor: middle; }}
    .node-subtitle {{ fill: #b4d4ee; font: 11px Arial, sans-serif; text-anchor: middle; }}
    .panel {{ fill: rgba(9, 32, 58, 0.72); stroke: rgba(96, 160, 214, 0.45); stroke-dasharray: 8 7; }}
    .metric {{ fill: #eaf8ff; font: 700 20px Arial, sans-serif; }}
  </style>
  <rect width="{width}" height="{height}" rx="24" class="bg"/>
  {_svg_grid(width, height)}
  <text x="34" y="48" class="small">LANGGRAPH PRACTICE TOPOLOGY</text>
  <text x="34" y="78" class="label">Dynamic Parallel Agent Demo</text>
  <text x="760" y="50" class="small">PAPERS {paper_count} / AGENTS {selected_count}</text>

  <rect x="300" y="105" width="380" height="225" rx="18" class="panel"/>
  <text x="490" y="132" class="small" text-anchor="middle">SERIAL PIPELINE</text>
  {_svg_circle_node(center_x, 175, 42, "Q", "normalize", node_class("normalize_question"))}
  <path class="edge {node_class("retrieve_papers")}" d="M {center_x} 218 L {center_x} 252" />
  {_svg_circle_node(center_x, 295, 42, "R", "retrieve", node_class("retrieve_papers"))}
  <path class="edge {node_class("route")}" d="M {center_x} 337 L {center_x} 365" />
  {_svg_circle_node(center_x, 405, 50, "ROUTE", "select agents", node_class("route"))}

  <rect x="{start_x}" y="420" width="660" height="120" rx="18" class="panel"/>
  <text x="490" y="445" class="small" text-anchor="middle">PARALLEL SEND BRANCHES</text>
  {agent_edges}
  {agent_nodes}

  <path class="edge {node_class("report")}" d="M {center_x} 540 L {center_x} 588" />
  {_svg_circle_node(center_x, 635, 50, "REPORT", "reduce outputs", node_class("report"))}

  <text x="34" y="622" class="small">RECENT TRACE</text>
  {trace_text}
</svg>
""".strip()


def _svg_circle_node(
    x: float,
    y: float,
    r: float,
    title: str,
    subtitle: str,
    css: str,
) -> str:
    return f"""
  <g class="{css}">
    <circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" class="node-circle"/>
    <text x="{x:.1f}" y="{y - 3:.1f}" class="node-title">{html.escape(title)}</text>
    <text x="{x:.1f}" y="{y + 18:.1f}" class="node-subtitle">{html.escape(subtitle)}</text>
  </g>
""".strip()


def _svg_grid(width: int, height: int) -> str:
    vertical = "\n".join(
        f'<line x1="{x}" y1="95" x2="{x}" y2="{height - 35}" class="grid"/>'
        for x in range(30, width, 38)
    )
    horizontal = "\n".join(
        f'<line x1="24" y1="{y}" x2="{width - 24}" y2="{y}" class="grid"/>'
        for y in range(105, height - 35, 38)
    )
    return vertical + "\n" + horizontal


def write_html_trace(query: str, output_path: Path) -> None:
    """Run the demo and save one final SVG visualization into an HTML file."""
    completed_nodes: set[str] = set()
    completed_agents: set[str] = set()
    active_node: str | None = None
    state = create_initial_state(query)
    for event in stream_demo(query):
        state = event["state"]
        node = event["node"]
        active_node = node
        if node == "run_agent" and event.get("agent_name"):
            completed_agents.add(event["agent_name"])
        else:
            completed_nodes.add(node)

    svg = render_svg(state, active_node, completed_nodes, completed_agents)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "<!doctype html><meta charset='utf-8'><title>LangGraph Practice</title>"
        "<body style='margin:0;background:#061427'>"
        f"{svg}</body>",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the LangGraph practice demo.")
    parser.add_argument(
        "query",
        nargs="?",
        default="Compare methods and limitations for KV cache compression.",
    )
    parser.add_argument(
        "--html",
        default="outputs/langgraph_practice_trace.html",
        help="Path for the generated HTML visualization.",
    )
    args = parser.parse_args()

    print("Streaming graph events:\n")
    for event in stream_demo(args.query):
        node = event["node"]
        agent = f" / {event['agent_name']}" if event.get("agent_name") else ""
        print(f"- {node}{agent}")

    final_state = run_demo(args.query)
    print("\nFinal answer:\n")
    print(final_state["final_answer"])

    write_html_trace(args.query, Path(args.html))
    print(f"\nVisualization written to: {args.html}")


if __name__ == "__main__":
    main()
