[theme]
primaryColor = "#147D64"
backgroundColor = "#F6F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E2926"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
